version: '3'

services:

    nginx:
        build: ./docker/nginx/
        ports:
            - 8080:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www

    php:
        build: ./docker/php/
        expose:
            - 9000
        volumes:
            - .:/var/www
            - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini